export enum FullyLinkedEventEnum {
    nodeClick = 'nodeClick',
    nodeDblClick = 'nodeDblClick',
    nodeRightClick = 'nodeRightClick',
    nodeDragStart = 'nodeDragStart',
    nodeDragEnd = 'nodeDragEnd',
    nodeDrag = 'nodeDrag',
    edgeClick = 'edgeClick',
    edgeDblClick = 'edgeDblClick',
    edgeRightClick = 'edgeRightClick',
    edgeCreationStart = 'edgeCreationStart',
    edgeCreationEndSuccessfully = 'edgeCreationEndSuccessfully',
    edgeCreationCancel = 'edgeCreationCancel',
    canvasClick = 'canvasClick',
    canvasDblClick = 'canvasDblClick',
    canvasRightClick = 'canvasRightClick',
    canvasDragStart = 'canvasDragStart',
    canvasDragEnd = 'canvasDragEnd',
    canvasDrag = 'canvasDrag',
    canvasZoom = 'canvasZoom',
    canvasZoomStart = 'canvasZoomStart',
    canvasZoomEnd = 'canvasZoomEnd',
}